# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 16:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=30, verbose_name='IMEI')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('studentid', models.CharField(max_length=30, verbose_name='学号')),
                ('score', models.FloatField(verbose_name='分数')),
                ('role', models.CharField(choices=[('student', '学生'), ('teacher', '教师')], default='student', max_length=20)),
                ('wifiname', models.CharField(max_length=30, verbose_name='wifi名称')),
                ('punchtime', models.DateTimeField(default=datetime.datetime.now, verbose_name='打卡时间')),
                ('teachername', models.CharField(max_length=30, verbose_name='教师姓名')),
            ],
            options={
                'verbose_name': '个人信息',
                'verbose_name_plural': '个人信息',
            },
        ),
    ]
