# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='商品ISBN')),
                ('name', models.CharField(max_length=50, verbose_name='商品名')),
                ('price', models.FloatField(verbose_name='商品价格')),
                ('image', models.ImageField(default='image/default.png', upload_to='image/%Y/%m')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
    ]
