# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 02:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='商品位置'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='isbn',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='商品编码'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=50, verbose_name='商品名称'),
        ),
    ]
