# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 19:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_auto_20170704_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号码')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('image', models.ImageField(upload_to='media/', verbose_name='图像')),
                ('age', models.IntegerField(max_length=3, verbose_name='年龄')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='MobileVerf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='短信验证码')),
                ('phonenum', models.CharField(max_length=11, verbose_name='手机号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '手机验证码',
                'verbose_name_plural': '手机验证码',
            },
        ),
        migrations.DeleteModel(
            name='MobileVerifyRecord',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
