# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_auto_20170704_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.RemoveField(
            model_name='customers',
            name='age',
        ),
    ]
