# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_remove_customers_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='订单总价')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.Customers', verbose_name='客户')),
            ],
            options={
                'verbose_name': '用户订单',
                'verbose_name_plural': '用户订单',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='商品数量')),
                ('goodsname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.Goods', verbose_name='商品名称')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.Order', verbose_name='订单号')),
            ],
            options={
                'verbose_name': '项目详细',
                'verbose_name_plural': '项目详细',
            },
        ),
    ]
