# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_auto_20170705_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id'], 'verbose_name': '用户订单', 'verbose_name_plural': '用户订单'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': '订单详细', 'verbose_name_plural': '订单详细'},
        ),
        migrations.AddField(
            model_name='orderitems',
            name='goodprice',
            field=models.FloatField(default=0, verbose_name='商品价格'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='goodsname',
            field=models.CharField(max_length=100, verbose_name='商品名'),
        ),
    ]
