# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0012_auto_20170705_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='商品数量'),
        ),
    ]
