# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0013_auto_20170705_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='订单号'),
        ),
    ]
