# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0016_auto_20170705_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordernum',
            field=models.IntegerField(default=None, unique=True, verbose_name='订单号'),
        ),
    ]
