# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 01:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0018_orderitems_is_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='is_end',
        ),
        migrations.AddField(
            model_name='goods',
            name='ingredient',
            field=models.CharField(default='', max_length=150, verbose_name='配料'),
        ),
        migrations.AddField(
            model_name='goods',
            name='productiondate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='生产日期'),
        ),
        migrations.AddField(
            model_name='goods',
            name='shelflife',
            field=models.IntegerField(default=1, verbose_name='保质期'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='imageurl',
            field=models.URLField(null=True, verbose_name='商品地址'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='is_degauss',
            field=models.CharField(choices=[('ok', '消磁'), ('no', '未消磁')], default='no', max_length=3, verbose_name='是否消磁'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='is_pay',
            field=models.BooleanField(default=False, verbose_name='是否支付'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='orderid',
            field=models.IntegerField(verbose_name='订单号'),
        ),
    ]
