# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0021_auto_20170709_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goodstype',
            field=models.CharField(default='', max_length=20, verbose_name='商品类型'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='ingredient',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='配料'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='shelflife',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='保质期'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='imageurl',
            field=models.URLField(null=True, verbose_name='图片地址'),
        ),
    ]
