# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0022_auto_20170709_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='shelflife',
            field=models.IntegerField(blank=True, null=True, verbose_name='保质期'),
        ),
    ]
