# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 13:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fromlabid', models.IntegerField(verbose_name='原存放地址ID')),
                ('device_image', models.ImageField(upload_to='device/', verbose_name='设备图片')),
                ('device_inlabid', models.IntegerField(verbose_name='现存放地址ID')),
                ('device_name', models.CharField(max_length=50, verbose_name='设备名称')),
                ('device_no', models.CharField(max_length=50, verbose_name='设备编号')),
                ('device_type', models.CharField(max_length=50, verbose_name='设备类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='Devicemove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(verbose_name='设备ID')),
                ('devicemove_fromlabid', models.IntegerField(verbose_name='移动实验编号')),
                ('devicemove_img', models.ImageField(upload_to='', verbose_name='摄像头拍照图片')),
                ('devicemove_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='设备移动时间')),
                ('devicemove_tolabid', models.IntegerField(verbose_name='移入实验编号')),
                ('user_id', models.ImageField(upload_to='', verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_address', models.CharField(max_length=50, verbose_name='实验室地址')),
                ('lab_getuiid', models.CharField(max_length=50, verbose_name='单片机推送ID')),
                ('lab_img', models.ImageField(upload_to='lab/', verbose_name='实验室图片')),
                ('lab_name', models.CharField(max_length=50, verbose_name='实验室名称')),
                ('lab_no', models.CharField(max_length=50, verbose_name='实验室编号')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_getuid', models.CharField(max_length=50, verbose_name='个推ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='用户名')),
                ('user_role', models.IntegerField(verbose_name='角色')),
                ('user_tel', models.CharField(max_length=50, unique=True, verbose_name=50)),
            ],
        ),
        migrations.CreateModel(
            name='Userlabrelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.IntegerField(unique=True, verbose_name='实验室ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='用户ID')),
            ],
        ),
    ]
