# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': '实验室设备', 'verbose_name_plural': '实验室设备'},
        ),
        migrations.AlterModelOptions(
            name='devicemove',
            options={'verbose_name': '移动设备记录', 'verbose_name_plural': '移动设备记录'},
        ),
        migrations.AlterModelOptions(
            name='lab',
            options={'verbose_name': '实验室', 'verbose_name_plural': '实验室'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '人员', 'verbose_name_plural': '人员'},
        ),
        migrations.AlterModelOptions(
            name='userlabrelated',
            options={'verbose_name': '人员-实验室关联表', 'verbose_name_plural': '人员-实验室关联表'},
        ),
    ]
